r"""Exact Riemann solver for the 1-D Euler equations.

The solver follows Toro, *Riemann Solvers and Numerical Methods for Fluid
Dynamics* (3rd ed.), chapter 4: the star pressure :math:`p_*` is the root of

.. math::

    f(p) = f_L(p, \mathbf{W}_L) + f_R(p, \mathbf{W}_R) + (u_R - u_L) = 0 ,

which is solved by a Newton iteration on a pressure that is kept positive at
every step.  Unlike the MATLAB prototype shipped with the report — which
hard-codes the *left rarefaction / right shock* pattern of Sod's problem — this
implementation handles all four wave patterns and detects vacuum generation, so
it can be used as a reference solution for any Riemann data.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from .thermo import GAMMA_AIR, sound_speed

__all__ = ["GasState", "StarState", "solve_star_state", "sample", "exact_solution"]


@dataclass(frozen=True)
class GasState:
    """A constant primitive state :math:`(\\rho, u, p)`."""

    rho: float
    u: float
    p: float

    def sound_speed(self, gamma: float = GAMMA_AIR) -> float:
        return float(sound_speed(self.rho, self.p, gamma))

    def as_tuple(self) -> tuple[float, float, float]:
        return (self.rho, self.u, self.p)


@dataclass(frozen=True)
class StarState:
    """Solution of the Riemann problem in the star region."""

    p: float
    u: float
    rho_left: float
    rho_right: float
    left_wave: str
    right_wave: str
    speeds: dict[str, float] = field(default_factory=dict)
    iterations: int = 0


def _f_and_derivative(
    p: float, state: GasState, gamma: float
) -> tuple[float, float]:
    """Pressure function of one side and its derivative (Toro, eq. 4.6-4.7)."""
    rho_k, p_k = state.rho, state.p
    a_k = state.sound_speed(gamma)
    if p > p_k:  # shock
        A_k = 2.0 / ((gamma + 1.0) * rho_k)
        B_k = (gamma - 1.0) / (gamma + 1.0) * p_k
        common = np.sqrt(A_k / (B_k + p))
        f = (p - p_k) * common
        df = common * (1.0 - 0.5 * (p - p_k) / (B_k + p))
    else:  # rarefaction
        ratio = p / p_k
        exponent = (gamma - 1.0) / (2.0 * gamma)
        f = 2.0 * a_k / (gamma - 1.0) * (ratio**exponent - 1.0)
        df = ratio ** (-(gamma + 1.0) / (2.0 * gamma)) / (rho_k * a_k)
    return float(f), float(df)


def _initial_guess(left: GasState, right: GasState, gamma: float) -> float:
    """Adaptive starting value for the Newton iteration (Toro, sec. 9.5)."""
    a_l, a_r = left.sound_speed(gamma), right.sound_speed(gamma)

    # Primitive-variable (linearised) estimate.
    p_pv = 0.5 * (left.p + right.p) - 0.125 * (right.u - left.u) * (
        left.rho + right.rho
    ) * (a_l + a_r)
    p_pv = max(p_pv, 1e-12)

    p_min, p_max = min(left.p, right.p), max(left.p, right.p)
    if p_max / p_min <= 2.0 and p_min <= p_pv <= p_max:
        return p_pv

    if p_pv < p_min:  # two-rarefaction approximation
        exponent = (gamma - 1.0) / (2.0 * gamma)
        numerator = a_l + a_r - 0.5 * (gamma - 1.0) * (right.u - left.u)
        denominator = a_l / left.p**exponent + a_r / right.p**exponent
        return float((numerator / denominator) ** (1.0 / exponent))

    # Two-shock approximation.
    g_l = np.sqrt(
        (2.0 / ((gamma + 1.0) * left.rho))
        / ((gamma - 1.0) / (gamma + 1.0) * left.p + p_pv)
    )
    g_r = np.sqrt(
        (2.0 / ((gamma + 1.0) * right.rho))
        / ((gamma - 1.0) / (gamma + 1.0) * right.p + p_pv)
    )
    p_ts = (g_l * left.p + g_r * right.p - (right.u - left.u)) / (g_l + g_r)
    return float(max(p_ts, 1e-12))


def solve_star_state(
    left: GasState,
    right: GasState,
    gamma: float = GAMMA_AIR,
    tol: float = 1e-12,
    max_iter: int = 100,
) -> StarState:
    """Solve for the star region and every wave speed of the Riemann fan.

    Raises
    ------
    ValueError
        If the data generate a vacuum, i.e. the pressure-positivity condition
        :math:`\\frac{2}{\\gamma-1}(a_L + a_R) > u_R - u_L` is violated.
    """
    a_l, a_r = left.sound_speed(gamma), right.sound_speed(gamma)
    if 2.0 / (gamma - 1.0) * (a_l + a_r) <= right.u - left.u:
        raise ValueError(
            "vacuum is generated by these initial data; the star region does not exist"
        )

    p = _initial_guess(left, right, gamma)
    du = right.u - left.u
    iterations = 0
    converged = False
    while iterations < max_iter and not converged:
        iterations += 1
        f_l, df_l = _f_and_derivative(p, left, gamma)
        f_r, df_r = _f_and_derivative(p, right, gamma)
        p_new = p - (f_l + f_r + du) / (df_l + df_r)
        p_new = max(p_new, 1e-12)  # keep the iterate admissible
        converged = 2.0 * abs(p_new - p) / (p_new + p) < tol
        p = p_new
    if not converged:  # pragma: no cover - only reachable for pathological data
        raise RuntimeError(
            f"Newton iteration for p* did not converge in {max_iter} iterations"
        )

    f_l, _ = _f_and_derivative(p, left, gamma)
    f_r, _ = _f_and_derivative(p, right, gamma)
    u_star = 0.5 * (left.u + right.u) + 0.5 * (f_r - f_l)

    speeds: dict[str, float] = {"contact": float(u_star)}

    # --- left wave -------------------------------------------------------
    if p > left.p:
        left_wave = "shock"
        rho_star_l = left.rho * (
            (p / left.p + (gamma - 1.0) / (gamma + 1.0))
            / ((gamma - 1.0) / (gamma + 1.0) * p / left.p + 1.0)
        )
        speeds["left_shock"] = left.u - a_l * np.sqrt(
            (gamma + 1.0) / (2.0 * gamma) * p / left.p + (gamma - 1.0) / (2.0 * gamma)
        )
    else:
        left_wave = "rarefaction"
        rho_star_l = left.rho * (p / left.p) ** (1.0 / gamma)
        a_star_l = a_l * (p / left.p) ** ((gamma - 1.0) / (2.0 * gamma))
        speeds["left_head"] = left.u - a_l
        speeds["left_tail"] = u_star - a_star_l

    # --- right wave ------------------------------------------------------
    if p > right.p:
        right_wave = "shock"
        rho_star_r = right.rho * (
            (p / right.p + (gamma - 1.0) / (gamma + 1.0))
            / ((gamma - 1.0) / (gamma + 1.0) * p / right.p + 1.0)
        )
        speeds["right_shock"] = right.u + a_r * np.sqrt(
            (gamma + 1.0) / (2.0 * gamma) * p / right.p + (gamma - 1.0) / (2.0 * gamma)
        )
    else:
        right_wave = "rarefaction"
        rho_star_r = right.rho * (p / right.p) ** (1.0 / gamma)
        a_star_r = a_r * (p / right.p) ** ((gamma - 1.0) / (2.0 * gamma))
        speeds["right_head"] = right.u + a_r
        speeds["right_tail"] = u_star + a_star_r

    return StarState(
        p=float(p),
        u=float(u_star),
        rho_left=float(rho_star_l),
        rho_right=float(rho_star_r),
        left_wave=left_wave,
        right_wave=right_wave,
        speeds={k: float(v) for k, v in speeds.items()},
        iterations=iterations,
    )


def _sample_point(
    xi: float, star: StarState, left: GasState, right: GasState, gamma: float
) -> tuple[float, float, float]:
    """Evaluate the self-similar solution along the ray ``xi = x / t``."""
    a_l, a_r = left.sound_speed(gamma), right.sound_speed(gamma)

    if xi <= star.u:  # left of the contact discontinuity
        if star.left_wave == "shock":
            if xi <= star.speeds["left_shock"]:
                return left.as_tuple()
            return (star.rho_left, star.u, star.p)
        if xi <= star.speeds["left_head"]:
            return left.as_tuple()
        if xi >= star.speeds["left_tail"]:
            return (star.rho_left, star.u, star.p)
        # inside the left rarefaction fan
        u = 2.0 / (gamma + 1.0) * (a_l + 0.5 * (gamma - 1.0) * left.u + xi)
        a = 2.0 / (gamma + 1.0) * (a_l + 0.5 * (gamma - 1.0) * (left.u - xi))
        rho = left.rho * (a / a_l) ** (2.0 / (gamma - 1.0))
        p = left.p * (a / a_l) ** (2.0 * gamma / (gamma - 1.0))
        return (rho, u, p)

    # right of the contact discontinuity
    if star.right_wave == "shock":
        if xi >= star.speeds["right_shock"]:
            return right.as_tuple()
        return (star.rho_right, star.u, star.p)
    if xi >= star.speeds["right_head"]:
        return right.as_tuple()
    if xi <= star.speeds["right_tail"]:
        return (star.rho_right, star.u, star.p)
    # inside the right rarefaction fan
    u = 2.0 / (gamma + 1.0) * (-a_r + 0.5 * (gamma - 1.0) * right.u + xi)
    a = 2.0 / (gamma + 1.0) * (a_r - 0.5 * (gamma - 1.0) * (right.u - xi))
    rho = right.rho * (a / a_r) ** (2.0 / (gamma - 1.0))
    p = right.p * (a / a_r) ** (2.0 * gamma / (gamma - 1.0))
    return (rho, u, p)


def sample(
    xi,
    left: GasState,
    right: GasState,
    gamma: float = GAMMA_AIR,
    star: StarState | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Sample the exact solution at one or many similarity coordinates."""
    star = star or solve_star_state(left, right, gamma)
    xi_arr = np.atleast_1d(np.asarray(xi, dtype=float))
    values = np.array(
        [_sample_point(float(s), star, left, right, gamma) for s in xi_arr.ravel()]
    )
    rho, u, p = (values[:, k].reshape(xi_arr.shape) for k in range(3))
    return rho, u, p


def exact_solution(
    x,
    t: float,
    left: GasState,
    right: GasState,
    gamma: float = GAMMA_AIR,
    x0: float = 0.5,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Exact primitive solution of a Riemann problem at time ``t``.

    At ``t = 0`` the initial discontinuity itself is returned.
    """
    x = np.asarray(x, dtype=float)
    if t <= 0.0:
        rho = np.where(x < x0, left.rho, right.rho)
        u = np.where(x < x0, left.u, right.u)
        p = np.where(x < x0, left.p, right.p)
        return rho, u, p
    return sample((x - x0) / t, left, right, gamma)
